<a href="https://colab.research.google.com/github/gblasd/DataScience/blob/BDCC/04_TCognitiveAndBigData/notebooks/TFquickstart.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Set up TensorFlow

In [3]:
import tensorflow as tf
print("TensorFlow version: ", tf.__version__)

TensorFlow version:  2.19.0


## Load a dataset

In [4]:
# Load and prepare the MNIST dataset
mnist = tf.keras.datasets.mnist

# Split data
(x_train, y_train), (x_test, y_test) = mnist.load_data()

# The pixel values of the images range from 0 through 255.
x_train, x_test = x_train / 255.0, x_test / 255.0

11490434/11490434 ━━━━━━━━━━━━━━━━━━━━ 0s 0us/step


## Build a machine learning model

In [5]:
# Sequential: stacking layers, one input tensor and one output tensor
model = tf.keras.models.Sequential([
  tf.keras.layers.Flatten(input_shape=(28, 28)),
  tf.keras.layers.Dense(128, activation='relu'),
  tf.keras.layers.Dropout(0.2),
  tf.keras.layers.Dense(10)
])

/usr/local/lib/python3.12/dist-packages/keras/src/layers/reshaping/flatten.py:37: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


In [6]:
# The model returns a vector of logits and probabilities for each class
predictions = model(x_train[:1]).numpy()
predictions

array([[-0.40692136,  0.27650103, -0.3272961 ,  0.5678088 , -0.53139126,
         0.6194774 ,  0.31845894,  0.16381551,  0.3356946 ,  0.30921638]],
      dtype=float32)

In [7]:
# Converts logits to probabilities for each class
tf.nn.softmax(predictions).numpy()

array([[0.05443371, 0.10781386, 0.05894525, 0.14427394, 0.04806305,
        0.15192431, 0.11243372, 0.09632429, 0.1143884 , 0.11139935]],
      dtype=float32)

In [8]:
# Define a loss function for training
loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)
loss_fn(y_train[:1], predictions).numpy()

np.float32(1.8843728)

In [9]:
# configure and compile the model
model.compile(
    optimizer='adam',
    loss=loss_fn,
    metrics=['accuracy']
    )

## Train and evaluate the model

In [10]:
# Adjust model parameters
model.fit(x_train, y_train, epochs=5)

Epoch 1/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 7s 3ms/step - accuracy: 0.8576 - loss: 0.4809
Epoch 2/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - accuracy: 0.9558 - loss: 0.1500
Epoch 3/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 6s 3ms/step - accuracy: 0.9672 - loss: 0.1079
Epoch 4/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 10s 3ms/step - accuracy: 0.9740 - loss: 0.0825
Epoch 5/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - accuracy: 0.9769 - loss: 0.0728


In [11]:
# Checks the model's performance
model.evaluate(x_test, y_test, verbose=2)

313/313 - 1s - 2ms/step - accuracy: 0.9787 - loss: 0.0708


[0.07080569863319397, 0.9786999821662903]

In [12]:
# Return a probability: wrap the trained model and attach the softmax
probability_model = tf.keras.Sequential([
  model,
  tf.keras.layers.Softmax()
])

# Call the model
probability_model(x_test[:5])

<tf.Tensor: shape=(5, 10), dtype=float32, numpy=
array([[4.21628599e-08, 4.76671680e-09, 5.09278652e-06, 2.67080250e-05,
        2.39957949e-11, 2.04102228e-08, 1.09854205e-12, 9.99965310e-01,
        6.29368984e-08, 2.77042682e-06],
       [1.13358041e-07, 1.19071294e-04, 9.99859214e-01, 1.88740723e-05,
        7.87536930e-15, 9.17839458e-08, 1.59127698e-08, 1.73305557e-13,
        2.61065611e-06, 1.66325829e-14],
       [7.68158372e-07, 9.88448203e-01, 2.21369695e-03, 7.42217162e-05,
        1.39952041e-04, 4.09049317e-05, 8.71008961e-05, 7.57064763e-03,
        1.42035424e-03, 4.28610701e-06],
       [9.99357164e-01, 4.42608687e-08, 1.45195518e-04, 5.71639384e-06,
        2.53518829e-06, 2.68639906e-06, 3.41034000e-04, 9.98272153e-05,
        6.99333285e-08, 4.58227223e-05],
       [2.33093601e-06, 1.74446207e-10, 2.17992283e-06, 1.06434591e-07,
        9.89594102e-01, 7.72037595e-07, 2.06222558e-06, 3.49553557e-05,
        1.09552317e-07, 1.03632985e-02]], dtype=float32)>

https://www.tensorflow.org/tutorials/quickstart/beginner