<a href="https://colab.research.google.com/github/gblasd/DataScience/blob/BDCC/04_TCognitiveAndBigData/notebooks/00__Introducci%C3%B3n_a_deep_learning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Deep learning (Intro)

## Preparación de ambiente

### Carga de módulos

In [1]:
# Misc
from warnings import filterwarnings

# Data wrangling
import h5py
import numpy as np
import pandas as pd

# Plotting
import cufflinks as cf

# Modeling
from keras.layers import Dense
from keras import metrics, Input
from sklearn.neural_network import MLPClassifier
from keras.models import Sequential, Model, load_model
from sklearn.model_selection import RandomizedSearchCV, GridSearchCV

# Preprocessing
from sklearn.preprocessing import MinMaxScaler
from tensorflow.keras.utils import to_categorical

# Model performance
from sklearn.metrics import accuracy_score, confusion_matrix
from sklearn.model_selection import train_test_split, cross_val_score

# Environment setup
filterwarnings("ignore")
cf.set_config_file(offline=True, theme="solar")

### Funciones auxiliares

In [2]:
def print_data(data):
    for row in data:
        print(''.join('{:3}'.format(value) for value in row))

## Data Wrangling

In [4]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


### Carga de datos

In [5]:
df = pd.read_csv("/content/drive/MyDrive/DataScience/data/digits_train_sample.csv")

In [ ]:
df

label  1x1  1x2  1x3  1x4  1x5  1x6  1x7  1x8  1x9  ...  28x19  28x20  \
0         3    0    0    0    0    0    0    0    0    0  ...      0      0   
1         5    0    0    0    0    0    0    0    0    0  ...      0      0   
2         3    0    0    0    0    0    0    0    0    0  ...      0      0   
3         8    0    0    0    0    0    0    0    0    0  ...      0      0   
4         0    0    0    0    0    0    0    0    0    0  ...      0      0   
...     ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...    ...    ...   
5995      5    0    0    0    0    0    0    0    0    0  ...      0      0   
5996      8    0    0    0    0    0    0    0    0    0  ...      0      0   
5997      2    0    0    0    0    0    0    0    0    0  ...      0      0   
5998      0    0    0    0    0    0    0    0    0    0  ...      0      0   
5999      8    0    0    0    0    0    0    0    0    0  ...      0      0   

      28x21  28x22  28x23  28x24  28x25  28x26  28x27  28x28  
0         0      0      0      0      0      0      0      0  
1         0      0      0      0      0      0      0      0  
2         0      0      0      0      0      0      0      0  
3         0      0      0      0      0      0      0      0  
4         0      0      0      0      0      0      0      0  
...     ...    ...    ...    ...    ...    ...    ...    ...  
5995      0      0      0      0      0      0      0      0  
5996      0      0      0      0      0      0      0      0  
5997      0      0      0      0      0      0      0      0  
5998      0      0      0      0      0      0      0      0  
5999      0      0      0      0      0      0      0      0  

[6000 rows x 785 columns]

### EDA

In [6]:
df

label  1x1  1x2  1x3  1x4  1x5  1x6  1x7  1x8  1x9  ...  28x19  28x20  \
0         3    0    0    0    0    0    0    0    0    0  ...      0      0   
1         5    0    0    0    0    0    0    0    0    0  ...      0      0   
2         3    0    0    0    0    0    0    0    0    0  ...      0      0   
3         8    0    0    0    0    0    0    0    0    0  ...      0      0   
4         0    0    0    0    0    0    0    0    0    0  ...      0      0   
...     ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...    ...    ...   
5995      5    0    0    0    0    0    0    0    0    0  ...      0      0   
5996      8    0    0    0    0    0    0    0    0    0  ...      0      0   
5997      2    0    0    0    0    0    0    0    0    0  ...      0      0   
5998      0    0    0    0    0    0    0    0    0    0  ...      0      0   
5999      8    0    0    0    0    0    0    0    0    0  ...      0      0   

      28x21  28x22  28x23  28x24  28x25  28x26  28x27  28x28  
0         0      0      0      0      0      0      0      0  
1         0      0      0      0      0      0      0      0  
2         0      0      0      0      0      0      0      0  
3         0      0      0      0      0      0      0      0  
4         0      0      0      0      0      0      0      0  
...     ...    ...    ...    ...    ...    ...    ...    ...  
5995      0      0      0      0      0      0      0      0  
5996      0      0      0      0      0      0      0      0  
5997      0      0      0      0      0      0      0      0  
5998      0      0      0      0      0      0      0      0  
5999      0      0      0      0      0      0      0      0  

[6000 rows x 785 columns]

In [7]:
for _ in range(5):
    number = df.sample()
    print(number["label"].values[0])
    number = number.drop(columns=["label"]).to_numpy().reshape((28, 28))
    print_data(number)

6
  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0 13184254255223 12  0  0  0  0  0  0
  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  5146253251244250 59  0  0  0  0  0  0
  0  0  0  0  0  0  0  0  0  0  0  0  0  0 13182253250 98  9 54  7  0  0  0  0  0  0
  0  0  0  0  0  0  0  0  0  0  0  0  0  8223253249103  0  0  0  0  0  0  0  0  0  0
  0  0  0  0  0  0  0  0  0  0  0  0 58204253252 98  0  0  0  0  0  0  0  0  0  0  0
  0  0  0  0  0  0  0  0  0  0  0 34196253253120  0  0  0  0  0  0  0  0  0  0  0  0
  0  0  0  0  0  0  0  0  0  0 11119250253203 60  0  0  0  0  0  0  0  0  0  0  0  0
  0  0  0  0  0  0  0  0  0  0101253253253 89  0  0  0  0  0  0  0  0  0  0  0  0  0
  0  0  0  0  0  0  0  0  0 29238253253143  1  0  0  0  0  0  0

### Preparación de sets

In [8]:
df

label  1x1  1x2  1x3  1x4  1x5  1x6  1x7  1x8  1x9  ...  28x19  28x20  \
0         3    0    0    0    0    0    0    0    0    0  ...      0      0   
1         5    0    0    0    0    0    0    0    0    0  ...      0      0   
2         3    0    0    0    0    0    0    0    0    0  ...      0      0   
3         8    0    0    0    0    0    0    0    0    0  ...      0      0   
4         0    0    0    0    0    0    0    0    0    0  ...      0      0   
...     ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...    ...    ...   
5995      5    0    0    0    0    0    0    0    0    0  ...      0      0   
5996      8    0    0    0    0    0    0    0    0    0  ...      0      0   
5997      2    0    0    0    0    0    0    0    0    0  ...      0      0   
5998      0    0    0    0    0    0    0    0    0    0  ...      0      0   
5999      8    0    0    0    0    0    0    0    0    0  ...      0      0   

      28x21  28x22  28x23  28x24  28x25  28x26  28x27  28x28  
0         0      0      0      0      0      0      0      0  
1         0      0      0      0      0      0      0      0  
2         0      0      0      0      0      0      0      0  
3         0      0      0      0      0      0      0      0  
4         0      0      0      0      0      0      0      0  
...     ...    ...    ...    ...    ...    ...    ...    ...  
5995      0      0      0      0      0      0      0      0  
5996      0      0      0      0      0      0      0      0  
5997      0      0      0      0      0      0      0      0  
5998      0      0      0      0      0      0      0      0  
5999      0      0      0      0      0      0      0      0  

[6000 rows x 785 columns]

In [9]:
X = df[[x for x in df.columns if x!= "label"]].astype(float).to_numpy()
y = df["label"].to_numpy()

In [10]:
df["label"].value_counts().reset_index()

label  count
0      7    677
1      1    671
2      8    628
3      0    603
4      9    594
5      6    591
6      3    583
7      2    567
8      4    546
9      5    540

In [11]:
df["label"].value_counts()

label
7    677
1    671
8    628
0    603
9    594
6    591
3    583
2    567
4    546
5    540
Name: count, dtype: int64

In [12]:
y

array([3, 5, 3, ..., 2, 0, 8])

In [13]:
y = to_categorical(y)

In [14]:
y

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 1., ..., 0., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.]])

In [15]:
y.shape

(6000, 10)

In [16]:
X_train, X_test, y_train, y_test = train_test_split(X, y)

### Escalado de datos

In [17]:
sc = MinMaxScaler()

In [18]:
X_train.max()

np.float64(255.0)

In [19]:
Xs = sc.fit_transform(X_train)

In [20]:
Xs.max()

np.float64(1.0)

## Modelado

### Generación de modelo

In [ ]:
Sequential?

Init signature: Sequential(layers=None, name=None)
Docstring:     
`Sequential` groups a linear stack of layers into a `tf.keras.Model`.

`Sequential` provides training and inference features on this model.

Examples:

```python
# Optionally, the first layer can receive an `input_shape` argument:
model = tf.keras.Sequential()
model.add(tf.keras.layers.Dense(8, input_shape=(16,)))
# Afterwards, we do automatic shape inference:
model.add(tf.keras.layers.Dense(4))

# This is identical to the following:
model = tf.keras.Sequential()
model.add(tf.keras.Input(shape=(16,)))
model.add(tf.keras.layers.Dense(8))

# Note that you can also omit the `input_shape` argument.
# In that case the model doesn't have any weights until the first call
# to a training/evaluation method (since it isn't yet built):
model = tf.keras.Sequential()
model.add(tf.keras.layers.Dense(8))
model.add(tf.keras.layers.Dense(4))
# model.weights not created yet

# Whereas if you specify the input shape, the model gets built


In [21]:
model = Sequential()

In [22]:
X_train.shape

(4500, 784)

### Capa de entrada

In [ ]:
Input?

Signature:
Input(
    shape=None,
    batch_size=None,
    name=None,
    dtype=None,
    sparse=None,
    tensor=None,
    ragged=None,
    type_spec=None,
    **kwargs,
)
Docstring:
`Input()` is used to instantiate a Keras tensor.

A Keras tensor is a symbolic tensor-like object, which we augment with
certain attributes that allow us to build a Keras model just by knowing the
inputs and outputs of the model.

For instance, if `a`, `b` and `c` are Keras tensors,
it becomes possible to do:
`model = Model(input=[a, b], output=c)`

Args:
    shape: A shape tuple (integers), not including the batch size.
        For instance, `shape=(32,)` indicates that the expected input
        will be batches of 32-dimensional vectors. Elements of this tuple
        can be None; 'None' elements represent dimensions where the shape is
        not known.
    batch_size: optional static batch size (integer).
    name: An optional name string for the layer.
        Should be unique in a model (do not reus

In [23]:
X_train.shape[1]

784

In [24]:
model.add(Input(shape=(X_train.shape[1],)))

In [25]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

### Capas ocultas

In [ ]:
Dense?

Init signature:
Dense(
    units,
    activation=None,
    use_bias=True,
    kernel_initializer='glorot_uniform',
    bias_initializer='zeros',
    kernel_regularizer=None,
    bias_regularizer=None,
    activity_regularizer=None,
    kernel_constraint=None,
    bias_constraint=None,
    **kwargs,
)
Docstring:     
Just your regular densely-connected NN layer.

`Dense` implements the operation:
`output = activation(dot(input, kernel) + bias)`
where `activation` is the element-wise activation function
passed as the `activation` argument, `kernel` is a weights matrix
created by the layer, and `bias` is a bias vector created by the layer
(only applicable if `use_bias` is `True`). These are all attributes of
`Dense`.

Note: If the input to the layer has a rank greater than 2, then `Dense`
computes the dot product between the `inputs` and the `kernel` along the
last axis of the `inputs` and axis 0 of the `kernel` (using `tf.tensordot`).
For example, if input has dimensions `(batch_size, d0

In [26]:
model.add(Dense(15, activation="tanh"))
model.add(Dense(30, activation="relu"))
model.add(Dense(50, activation="tanh"))
model.add(Dense(30, activation="sigmoid"))
model.add(Dense(15, activation="relu"))

In [27]:
15*784

11760

In [28]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                   │ (None, 15)             │        11,775 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 30)             │           480 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_2 (Dense)                 │ (None, 50)             │         1,550 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_3 (Dense)                 │ (None, 30)             │         1,530 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_4 (Dense)                 │ (None, 15)             │           465 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 15,800 (61.72 KB)

 Trainable params: 15,800 (61.72 KB)

 Non-trainable params: 0 (0.00 B)

### Capa de salida

In [29]:
# # Clasificación binaria
# model.add(Dense(1, activation="sigmoid"))

In [30]:
# # Regresión
# model.add(Dense(1, activation="linear"))

In [31]:
# Clasificación Multiclase
model.add(Dense(y.shape[1], activation="softmax"))

In [32]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                   │ (None, 15)             │        11,775 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 30)             │           480 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_2 (Dense)                 │ (None, 50)             │         1,550 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_3 (Dense)                 │ (None, 30)             │         1,530 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_4 (Dense)                 │ (None, 15)             │           465 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_5 (Dense)                 │ (None, 10)             │           160 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 15,960 (62.34 KB)

 Trainable params: 15,960 (62.34 KB)

 Non-trainable params: 0 (0.00 B)

### Configuración del modelo

In [ ]:
model.compile?

Signature:
model.compile(
    optimizer='rmsprop',
    loss=None,
    metrics=None,
    loss_weights=None,
    weighted_metrics=None,
    run_eagerly=None,
    steps_per_execution=None,
    jit_compile=None,
    **kwargs,
)
Docstring:
Configures the model for training.

Example:

```python
model.compile(optimizer=tf.keras.optimizers.Adam(learning_rate=1e-3),
              loss=tf.keras.losses.BinaryCrossentropy(),
              metrics=[tf.keras.metrics.BinaryAccuracy(),
                       tf.keras.metrics.FalseNegatives()])
```

Args:
    optimizer: String (name of optimizer) or optimizer instance. See
      `tf.keras.optimizers`.
    loss: Loss function. May be a string (name of loss function), or
      a `tf.keras.losses.Loss` instance. See `tf.keras.losses`. A loss
      function is any callable with the signature `loss = fn(y_true,
      y_pred)`, where `y_true` are the ground truth values, and
      `y_pred` are the model's predictions.
      `y_true` should have shape
      

* Regression Loss Functions
  * Mean Squared Error Loss ("mean_squared_error")
  * Mean Squared Logarithmic Error Loss ("mean_squared_logarithmic_error")
  * Mean Absolute Error Loss ("mean_absolute_error")
* Binary Classification Loss Functions
  * Binary Cross-Entropy ("binary_crossentropy")
  * Hinge Loss ("hinge")
  * Squared Hinge Loss ("squared_hinge")
* Multi-Class Classification Loss Functions
  * Multi-Class Cross-Entropy Loss ("categorical_crossentropy")
  * Sparse Multiclass Cross-Entropy Loss ("sparse_categorical_crossentropy")
  * Kullback Leibler Divergence Loss ("kullback_leibler_divergence")

In [33]:
model.compile(loss = "categorical_crossentropy", optimizer = "adam", metrics=["accuracy"])

### Entrenamiento del modelo

In [34]:
Xs.shape

(4500, 784)

In [35]:
model.fit(x = Xs, y=y_train, epochs=500, validation_data=(sc.transform(X_test), y_test))

Epoch 1/500
141/141 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - accuracy: 0.1591 - loss: 2.1722 - val_accuracy: 0.4640 - val_loss: 1.5738
Epoch 2/500
141/141 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.5503 - loss: 1.3612 - val_accuracy: 0.7253 - val_loss: 1.0090
Epoch 3/500
141/141 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7791 - loss: 0.8632 - val_accuracy: 0.8287 - val_loss: 0.7645
Epoch 4/500
141/141 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8629 - loss: 0.6013 - val_accuracy: 0.8447 - val_loss: 0.6513
Epoch 5/500
141/141 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8942 - loss: 0.4577 - val_accuracy: 0.8653 - val_loss: 0.5785
Epoch 6/500
141/141 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9175 - loss: 0.3648 - val_accuracy: 0.8753 - val_loss: 0.5257
Epoch 7/500
141/141 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.9304 - loss: 0.2994 - val_accuracy: 0.8713 - val_loss: 0.5278
Epoch 8/500
141/141 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.9397 - loss: 0.2627 - val_accu

### Análisis de resultados

In [36]:
dc_history = model.history.history

In [37]:
accuracy = pd.DataFrame(dc_history)

### Predicción

In [38]:
model.predict(Xs)

141/141 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step


array([[1.7992443e-07, 7.1749300e-09, 9.9999744e-01, ..., 2.1534554e-08,
        1.0547732e-06, 7.6000655e-09],
       [2.0406901e-13, 6.3582255e-09, 4.1129027e-11, ..., 1.5906540e-15,
        9.9999958e-01, 4.8962296e-09],
       [9.9995226e-01, 8.4702636e-09, 1.2398020e-07, ..., 3.7724677e-09,
        4.1486273e-05, 7.8841378e-09],
       ...,
       [2.8761206e-12, 7.7889097e-18, 4.7786943e-19, ..., 2.7016844e-16,
        3.9033651e-07, 1.0179921e-06],
       [3.5390426e-09, 1.0678502e-22, 2.3790777e-07, ..., 9.0944884e-11,
        1.6855227e-15, 3.7700030e-08],
       [2.4852992e-10, 8.5191132e-08, 5.5394764e-08, ..., 5.6611892e-16,
        2.7091585e-07, 1.3051324e-13]], dtype=float32)

In [39]:
np.argmax(model.predict(Xs), axis=1)

141/141 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step


array([2, 8, 0, ..., 5, 6, 3])

In [40]:
list(map(np.argmax, y_train))

[np.int64(2),
 np.int64(8),
 np.int64(0),
 np.int64(6),
 np.int64(1),
 np.int64(4),
 np.int64(6),
 np.int64(4),
 np.int64(5),
 np.int64(6),
 np.int64(9),
 np.int64(0),
 np.int64(4),
 np.int64(1),
 np.int64(7),
 np.int64(9),
 np.int64(3),
 np.int64(9),
 np.int64(7),
 np.int64(9),
 np.int64(8),
 np.int64(5),
 np.int64(4),
 np.int64(4),
 np.int64(1),
 np.int64(3),
 np.int64(4),
 np.int64(9),
 np.int64(3),
 np.int64(2),
 np.int64(4),
 np.int64(3),
 np.int64(8),
 np.int64(4),
 np.int64(4),
 np.int64(9),
 np.int64(9),
 np.int64(0),
 np.int64(1),
 np.int64(9),
 np.int64(7),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(5),
 np.int64(2),
 np.int64(4),
 np.int64(6),
 np.int64(0),
 np.int64(7),
 np.int64(8),
 np.int64(2),
 np.int64(3),
 np.int64(5),
 np.int64(2),
 np.int64(2),
 np.int64(2),
 np.int64(8),
 np.int64(7),
 np.int64(9),
 np.int64(1),
 np.int64(8),
 np.int64(4),
 np.int64(1),
 np.int64(4),
 np.int64(1),
 np.int64(1),
 np.int64(0),
 np.int64(6),
 np.int64(0),
 np.int64(4),
 np.in

In [41]:
accuracy_score(y_pred=np.argmax(model.predict(Xs), axis=1), y_true=list(map(np.argmax, y_train)))

141/141 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step


1.0

In [42]:
accuracy_score(y_pred=np.argmax(model.predict(sc.transform(X_test)), axis=1), y_true=list(map(np.argmax, y_test)))

47/47 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step


0.8946666666666667

In [43]:
validate = pd.read_csv("/content/drive/MyDrive/DataScience/data/digits_test_sample.csv")

In [44]:
X_val = validate[[x for x in validate.columns if x!= "label"]].astype(float).to_numpy()
y_val = validate["label"].to_numpy()

In [45]:
accuracy_score(y_pred=np.argmax(model.predict(sc.transform(X_val)), axis=1), y_true=list(map(np.argmax, to_categorical(y_val))))

32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step 


0.9

* train: 1
* test: 0.896
* val: 0.889

### Preservación del modelo

In [46]:
model.save('./deep_model.h5')

In [47]:
new_model = load_model('./deep_model.h5')

In [48]:
new_model.predict(Xs)

141/141 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step


array([[1.7992443e-07, 7.1749300e-09, 9.9999744e-01, ..., 2.1534554e-08,
        1.0547732e-06, 7.6000655e-09],
       [2.0406901e-13, 6.3582255e-09, 4.1129027e-11, ..., 1.5906540e-15,
        9.9999958e-01, 4.8962296e-09],
       [9.9995226e-01, 8.4702636e-09, 1.2398020e-07, ..., 3.7724677e-09,
        4.1486273e-05, 7.8841378e-09],
       ...,
       [2.8761206e-12, 7.7889097e-18, 4.7786943e-19, ..., 2.7016844e-16,
        3.9033651e-07, 1.0179921e-06],
       [3.5390426e-09, 1.0678502e-22, 2.3790777e-07, ..., 9.0944884e-11,
        1.6855227e-15, 3.7700030e-08],
       [2.4852992e-10, 8.5191132e-08, 5.5394764e-08, ..., 5.6611892e-16,
        2.7091585e-07, 1.3051324e-13]], dtype=float32)

In [49]:
f = h5py.File('./deep_model.h5', 'r')
print(list(f.keys()))

['model_weights', 'optimizer_weights']


In [50]:
f["model_weights"]["dense"]

<HDF5 group "/model_weights/dense" (1 members)>